# Configuration of Hugo
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Santiago Montoya-Blandón
baseURL: 'https://smontoy.netlify.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir: false
removePathAccents: true # Workaround for https://github.com/gohugoio/hugo/issues/5687

############################
## PAGE OPTIONS
############################

cascade:
  - target:
      path: /slides/**
      kind: page
    outputs: [HTML, present]

############################
## ADVANCED
############################

enableGitInfo: false
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true

outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]

mediaTypes:
  application/manifest+json:
    suffixes: [webmanifest]
  text/netlify:
    delimiter: ''
    suffixes: ['']

outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
  headers:
    baseName: _headers
    isPlainText: true
    mediaType: text/netlify
    notAlternative: true
  redirects:
    baseName: _redirects
    isPlainText: true
    mediaType: text/netlify
    notAlternative: true

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true # Enable user to embed HTML snippets in Markdown content.
    parser:
      attribute:
        block: true
        title: true
  highlight:
    codeFences: false # Disable Hugo's code highlighter as it conflicts with the theme's highlighter.
    lineNos: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

security:
  funcs:
    getenv: ["^HUGO_", "^WC_"]
