# SITE SETUP

############################
## Theme
############################

# Choose a theme (browse built-in themes in `data/themes/`, or your own in `data/themes/`).
theme: uofg

# Enable users to switch between day and night mode?
day_night: true

# Override the theme's font set (browse built-in font sets in `data/fonts/`).
font: customfont

# Choose a font size. Sizes: XS, S, M, L (default), XL
font_size: L

############################
## Basic Info
############################

site_type: Person
local_business_type: ''
org_name: ''
description: 'Santiago Montoya Blandon University of Glasgow Adam Smith Business School Lecturer of Econometrics'
logo: ''

############################
## Site Features
############################

highlight: true
highlight_languages: ['r', 'latex']

math: true
diagram: false
privacy_pack: true

edit_page:
  repo_url: 'https://github.com/smonto2/Website'
  repo_branch: master
  editable:
    docs: true
    page: false
    post: false

############################
## Social
############################

sharing_image: ''
twitter: SMontoyaBlandon

############################
## Regional Settings
############################

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

############################
## Advanced
############################

main_menu:
  align: l
  show_logo: true
  show_language: true

avatar:
  gravatar: false
  shape: circle
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
link_authors: true
plugins_js: []

publications:
  date_format: 'January 2006'
  citation_style: apa

projects:
  post_view: 2
  publication_view: 2
  talk_view: 2

address_formats:
  en-us:
    order: ['street', 'city', 'region', 'postcode']
    delimiters: [', ', ', ', ' ', '']
  en-gb:
    order: ['street', 'city', 'region', 'postcode']
    delimiters: [', ', ', ', ', ', '']
  zh:
    order: ['postcode', 'region', 'city', 'street']
    delimiters: [' ', ' ', ' ', '']

############################
## Comments
############################

comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true

############################
## Search
############################

search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

############################
## Maps
############################

map:
  provider: ''
  api_key: ''
  zoom: 15

############################
## Marketing
############################

marketing:
  google_analytics: ''
  google_tag_manager: ''

############################
## Icon Pack Extensions
############################

icon:
  pack:
    ai: true # Academicons icon pack https://jpswalsh.github.io/academicons/
